FROM openjdk:17-oracle
COPY /build/libs/schoolbus-0.0.1-SNAPSHOT.jar /bin/runner/run.jar
WORKDIR /bin/runner
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
EXPOSE 8080
CMD ["java","-jar","run.jar"]